[package]
name = "user_interface"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["all-machines"]
pc98 = ["machine_factory/pc98"]
pc88 = ["machine_factory/pc88"]
pc88va = ["machine_factory/pc88va"]
pc60 = ["machine_factory/pc60"]
msx = ["machine_factory/msx"]
towns = ["machine_factory/towns"]
x1 = ["machine_factory/x1"]
fm7 = ["machine_factory/fm7"]
x68k = ["machine_factory/x68k"]
at = ["machine_factory/at"]
all-machines = ["pc98", "pc88", "pc88va", "pc60", "msx", "towns", "x1", "fm7", "x68k", "at"]
mt32 = ["machine_factory/mt32"]
sc55 = ["machine_factory/sc55"]
sdl3-build-from-source = ["sdl3/build-from-source"]
sdl3-use-pkg-config = ["sdl3/use-pkg-config"]
sdl3-use-vcpkg = ["sdl3/use-vcpkg"]

[dependencies]
audio_engine = { workspace = true }
common = { workspace = true, features = ["std"] }
device = { workspace = true }
machine_factory = { workspace = true }
dos = { workspace = true }
save_state = { workspace = true }
sdl3 = { workspace = true }
sdl3_backend = { workspace = true }
software_renderer = { workspace = true }
text_extractor = { workspace = true }

[dev-dependencies]
machine_60 = { workspace = true }
machine_msx = { workspace = true }
machine_x68k = { workspace = true }
