[package]
name = "machine_fm7"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common = { workspace = true, features = ["std"] }
cpu.workspace = true
device.workspace = true
software_renderer = { workspace = true, features = ["std"] }
rom_loader.workspace = true
save_state = { workspace = true, features = ["std"] }
