[package]
name = "munt_oxide"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "LGPL-2.1-or-later"

[dependencies]
blake3.workspace = true
common = { workspace = true, features = ["std"] }
resampler.workspace = true
save_state.workspace = true
