//! Machine-native key name lookups for `key.*` config overrides.
//!
//! Each `key.<host> = <native>` config binding names a host key on the left and a
//! machine-native key on the right. The parsers here resolve the right-hand name
//! into the raw native code for a target family, bypassing the neutral host-key
//! path. This namespace is machine-specific, so every family has its own table.
//! Each family exposes a single `*_from_name` table; `parse_key_binding` routes a
//! target to its table and pairs the result with the host scancode.

use machine_factory::config::Target;
use sdl3::keyboard::Scancode;

/// Parses a `0xNN` literal into a raw key code. Targets that allow binding a raw
/// native code directly (PC-6001 and PC/AT) accept this form.
fn raw_hex_code(name: &str) -> Option<u8> {
    let hex = name
        .strip_prefix("0x")
        .or_else(|| name.strip_prefix("0X"))?;
    u8::from_str_radix(hex, 16).ok()
}

pub fn pc98_scancode_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "esc" => 0x00,
        "1" => 0x01,
        "2" => 0x02,
        "3" => 0x03,
        "4" => 0x04,
        "5" => 0x05,
        "6" => 0x06,
        "7" => 0x07,
        "8" => 0x08,
        "9" => 0x09,
        "0" => 0x0A,
        "minus" => 0x0B,
        "caret" => 0x0C,
        "yen" => 0x0D,
        "bs" => 0x0E,
        "tab" => 0x0F,
        "q" => 0x10,
        "w" => 0x11,
        "e" => 0x12,
        "r" => 0x13,
        "t" => 0x14,
        "y" => 0x15,
        "u" => 0x16,
        "i" => 0x17,
        "o" => 0x18,
        "p" => 0x19,
        "at" => 0x1A,
        "leftbracket" => 0x1B,
        "return" => 0x1C,
        "a" => 0x1D,
        "s" => 0x1E,
        "d" => 0x1F,
        "f" => 0x20,
        "g" => 0x21,
        "h" => 0x22,
        "j" => 0x23,
        "k" => 0x24,
        "l" => 0x25,
        "semicolon" => 0x26,
        "colon" => 0x27,
        "rightbracket" => 0x28,
        "z" => 0x29,
        "x" => 0x2A,
        "c" => 0x2B,
        "v" => 0x2C,
        "b" => 0x2D,
        "n" => 0x2E,
        "m" => 0x2F,
        "comma" => 0x30,
        "period" => 0x31,
        "slash" => 0x32,
        "underscore" => 0x33,
        "space" => 0x34,
        "xfer" => 0x35,
        "rollup" => 0x36,
        "rolldown" => 0x37,
        "ins" => 0x38,
        "del" => 0x39,
        "up" => 0x3A,
        "left" => 0x3B,
        "right" => 0x3C,
        "down" => 0x3D,
        "home" => 0x3E,
        "help" => 0x3F,
        "kpminus" => 0x40,
        "kpdivide" => 0x41,
        "kp7" => 0x42,
        "kp8" => 0x43,
        "kp9" => 0x44,
        "kpmultiply" => 0x45,
        "kp4" => 0x46,
        "kp5" => 0x47,
        "kp6" => 0x48,
        "kpplus" => 0x49,
        "kp1" => 0x4A,
        "kp2" => 0x4B,
        "kp3" => 0x4C,
        "kpequals" => 0x4D,
        "kp0" => 0x4E,
        "kpcomma" => 0x4F,
        "kpperiod" => 0x50,
        "nfer" => 0x51,
        "vf1" => 0x52,
        "vf2" => 0x53,
        "vf3" => 0x54,
        "vf4" => 0x55,
        "vf5" => 0x56,
        "stop" => 0x60,
        "copy" => 0x61,
        "f1" => 0x62,
        "f2" => 0x63,
        "f3" => 0x64,
        "f4" => 0x65,
        "f5" => 0x66,
        "f6" => 0x67,
        "f7" => 0x68,
        "f8" => 0x69,
        "f9" => 0x6A,
        "f10" => 0x6B,
        "shift" => 0x70,
        "caps" => 0x71,
        "kana" => 0x72,
        "grph" => 0x73,
        "ctrl" => 0x74,
        _ => return None,
    })
}

/// Maps an X68000 key name to its native `row << 3 | column` code.
pub fn x68k_scancode_from_name(name: &str) -> Option<u8> {
    let name = name.to_ascii_lowercase();
    Some(match name.as_str() {
        "esc" => 0x01,
        "1" => 0x02,
        "2" => 0x03,
        "3" => 0x04,
        "4" => 0x05,
        "5" => 0x06,
        "6" => 0x07,
        "7" => 0x08,
        "8" => 0x09,
        "9" => 0x0A,
        "0" => 0x0B,
        "minus" => 0x0C,
        "caret" => 0x0D,
        "yen" => 0x0E,
        "bs" => 0x0F,
        "tab" => 0x10,
        "q" => 0x11,
        "w" => 0x12,
        "e" => 0x13,
        "r" => 0x14,
        "t" => 0x15,
        "y" => 0x16,
        "u" => 0x17,
        "i" => 0x18,
        "o" => 0x19,
        "p" => 0x1A,
        "at" => 0x1B,
        "leftbracket" => 0x1C,
        "return" => 0x1D,
        "a" => 0x1E,
        "s" => 0x1F,
        "d" => 0x20,
        "f" => 0x21,
        "g" => 0x22,
        "h" => 0x23,
        "j" => 0x24,
        "k" => 0x25,
        "l" => 0x26,
        "semicolon" => 0x27,
        "colon" => 0x28,
        "rightbracket" => 0x29,
        "z" => 0x2A,
        "x" => 0x2B,
        "c" => 0x2C,
        "v" => 0x2D,
        "b" => 0x2E,
        "n" => 0x2F,
        "m" => 0x30,
        "comma" => 0x31,
        "period" => 0x32,
        "slash" => 0x33,
        "underscore" => 0x34,
        "space" => 0x35,
        "home" => 0x36,
        "del" => 0x37,
        "rollup" => 0x38,
        "rolldown" => 0x39,
        "undo" => 0x3A,
        "left" => 0x3B,
        "up" => 0x3C,
        "right" => 0x3D,
        "down" => 0x3E,
        "clear" => 0x3F,
        "kpdivide" => 0x40,
        "kpmultiply" => 0x41,
        "kpminus" => 0x42,
        "kp7" => 0x43,
        "kp8" => 0x44,
        "kp9" => 0x45,
        "kpplus" => 0x46,
        "kp4" => 0x47,
        "kp5" => 0x48,
        "kp6" => 0x49,
        "kpequals" => 0x4A,
        "kp1" => 0x4B,
        "kp2" => 0x4C,
        "kp3" => 0x4D,
        "kpenter" => 0x4E,
        "kp0" => 0x4F,
        "kpcomma" => 0x50,
        "kpperiod" => 0x51,
        "symbol" => 0x52,
        "register" => 0x53,
        "help" => 0x54,
        "xf1" => 0x55,
        "xf2" => 0x56,
        "xf3" => 0x57,
        "xf4" => 0x58,
        "xf5" => 0x59,
        "kana" => 0x5A,
        "romaji" => 0x5B,
        "code" => 0x5C,
        "caps" => 0x5D,
        "ins" => 0x5E,
        "hiragana" => 0x5F,
        "fullwidth" => 0x60,
        "break" => 0x61,
        "copy" => 0x62,
        "f1" => 0x63,
        "f2" => 0x64,
        "f3" => 0x65,
        "f4" => 0x66,
        "f5" => 0x67,
        "f6" => 0x68,
        "f7" => 0x69,
        "f8" => 0x6A,
        "f9" => 0x6B,
        "f10" => 0x6C,
        "shift" => 0x70,
        "ctrl" => 0x71,
        "opt1" => 0x72,
        "opt2" => 0x73,
        _ => return None,
    })
}

/// Maps a PC-88VA key name to its keycode (the value read at port 0x1C1). The VA
/// keycode interface reuses the PC-98 scan-code protocol, so this defers to the
/// PC-98 name table and adds the few VA-only keys.
pub fn pc88va_keycode_from_name(name: &str) -> Option<u8> {
    if let Some(code) = pc98_scancode_from_name(name) {
        return Some(code);
    }
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "henkan" | "convert" => 0x35,
        "kettei" | "decide" => 0x51,
        "pc" => 0x7A,
        "zenkaku" => 0x7B,
        _ => return None,
    })
}

/// Maps an FM Towns key name to its JIS scancode (the second byte of the
/// keyboard's serial packet).
pub fn towns_scancode_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "esc" => 0x01,
        "1" => 0x02,
        "2" => 0x03,
        "3" => 0x04,
        "4" => 0x05,
        "5" => 0x06,
        "6" => 0x07,
        "7" => 0x08,
        "8" => 0x09,
        "0" => 0x0B,
        "9" => 0x0A,
        "minus" => 0x0C,
        "caret" => 0x0D,
        "yen" => 0x0E,
        "bs" => 0x0F,
        "tab" => 0x10,
        "q" => 0x11,
        "w" => 0x12,
        "e" => 0x13,
        "r" => 0x14,
        "t" => 0x15,
        "y" => 0x16,
        "u" => 0x17,
        "i" => 0x18,
        "o" => 0x19,
        "p" => 0x1A,
        "at" => 0x1B,
        "leftbracket" => 0x1C,
        "return" => 0x1D,
        "a" => 0x1E,
        "s" => 0x1F,
        "d" => 0x20,
        "f" => 0x21,
        "g" => 0x22,
        "h" => 0x23,
        "j" => 0x24,
        "k" => 0x25,
        "l" => 0x26,
        "semicolon" => 0x27,
        "colon" => 0x28,
        "rightbracket" => 0x29,
        "z" => 0x2A,
        "x" => 0x2B,
        "c" => 0x2C,
        "v" => 0x2D,
        "b" => 0x2E,
        "n" => 0x2F,
        "m" => 0x30,
        "comma" => 0x31,
        "period" => 0x32,
        "slash" => 0x33,
        "underscore" => 0x34,
        "space" => 0x35,
        "kpmultiply" => 0x36,
        "kpdivide" => 0x37,
        "kpplus" => 0x38,
        "kpminus" => 0x39,
        "kp7" => 0x3A,
        "kp8" => 0x3B,
        "kp9" => 0x3C,
        "kp4" => 0x3E,
        "kp5" => 0x3F,
        "kp6" => 0x40,
        "kp1" => 0x42,
        "kp2" => 0x43,
        "kp3" => 0x44,
        "kpenter" => 0x45,
        "kp0" => 0x46,
        "kpperiod" => 0x47,
        "ins" => 0x48,
        "del" => 0x4B,
        "up" => 0x4D,
        "home" => 0x4E,
        "left" => 0x4F,
        "down" => 0x50,
        "right" => 0x51,
        "ctrl" => 0x52,
        "shift" => 0x53,
        "caps" => 0x55,
        "alt" => 0x5C,
        "f1" => 0x5D,
        "f2" => 0x5E,
        "f3" => 0x5F,
        "f4" => 0x60,
        "f5" => 0x61,
        "f6" => 0x62,
        "f7" => 0x63,
        "f8" => 0x64,
        "f9" => 0x65,
        "f10" => 0x66,
        "f11" => 0x69,
        "f12" => 0x5B,
        "cancel" => 0x72,
        "execute" => 0x73,
        "break" => 0x7C,
        "copy" => 0x7D,
        _ => return None,
    })
}

/// Encodes a PC-88 keyboard matrix position as `row << 3 | column`. The high bit
/// stays clear so the forwarding layer can set it to mark a key release.
const fn pc88_cell(row: u8, column: u8) -> u8 {
    (row << 3) | column
}

/// Maps a PC-88 key name to its matrix code, used for `key.*` config overrides.
/// Cells follow the standard PC-8801 keyboard matrix (ports 0x00-0x0E).
pub fn pc88_matrix_code_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        // Numeric keypad (matrix rows 0-1).
        "kp0" => pc88_cell(0, 0),
        "kp1" => pc88_cell(0, 1),
        "kp2" => pc88_cell(0, 2),
        "kp3" => pc88_cell(0, 3),
        "kp4" => pc88_cell(0, 4),
        "kp5" => pc88_cell(0, 5),
        "kp6" => pc88_cell(0, 6),
        "kp7" => pc88_cell(0, 7),
        "kp8" => pc88_cell(1, 0),
        "kp9" => pc88_cell(1, 1),
        "kpmultiply" => pc88_cell(1, 2),
        "kpplus" => pc88_cell(1, 3),
        "kpequals" => pc88_cell(1, 4),
        "kpcomma" => pc88_cell(1, 5),
        "kpperiod" => pc88_cell(1, 6),
        "return" | "kpenter" => pc88_cell(1, 7),
        // '@' and letters (matrix rows 2-5).
        "at" => pc88_cell(2, 0),
        "a" => pc88_cell(2, 1),
        "b" => pc88_cell(2, 2),
        "c" => pc88_cell(2, 3),
        "d" => pc88_cell(2, 4),
        "e" => pc88_cell(2, 5),
        "f" => pc88_cell(2, 6),
        "g" => pc88_cell(2, 7),
        "h" => pc88_cell(3, 0),
        "i" => pc88_cell(3, 1),
        "j" => pc88_cell(3, 2),
        "k" => pc88_cell(3, 3),
        "l" => pc88_cell(3, 4),
        "m" => pc88_cell(3, 5),
        "n" => pc88_cell(3, 6),
        "o" => pc88_cell(3, 7),
        "p" => pc88_cell(4, 0),
        "q" => pc88_cell(4, 1),
        "r" => pc88_cell(4, 2),
        "s" => pc88_cell(4, 3),
        "t" => pc88_cell(4, 4),
        "u" => pc88_cell(4, 5),
        "v" => pc88_cell(4, 6),
        "w" => pc88_cell(4, 7),
        "x" => pc88_cell(5, 0),
        "y" => pc88_cell(5, 1),
        "z" => pc88_cell(5, 2),
        // Symbol cluster (matrix row 5).
        "leftbracket" => pc88_cell(5, 3),
        "yen" => pc88_cell(5, 4),
        "rightbracket" => pc88_cell(5, 5),
        "caret" => pc88_cell(5, 6),
        "minus" => pc88_cell(5, 7),
        // Digits (matrix rows 6-7).
        "0" => pc88_cell(6, 0),
        "1" => pc88_cell(6, 1),
        "2" => pc88_cell(6, 2),
        "3" => pc88_cell(6, 3),
        "4" => pc88_cell(6, 4),
        "5" => pc88_cell(6, 5),
        "6" => pc88_cell(6, 6),
        "7" => pc88_cell(6, 7),
        "8" => pc88_cell(7, 0),
        "9" => pc88_cell(7, 1),
        // Punctuation (matrix row 7).
        "colon" => pc88_cell(7, 2),
        "semicolon" => pc88_cell(7, 3),
        "comma" => pc88_cell(7, 4),
        "period" => pc88_cell(7, 5),
        "slash" => pc88_cell(7, 6),
        "underscore" => pc88_cell(7, 7),
        // Control cluster (matrix row 8).
        "home" => pc88_cell(8, 0),
        "up" => pc88_cell(8, 1),
        "right" => pc88_cell(8, 2),
        "del" | "ins" | "bs" => pc88_cell(8, 3),
        "grph" => pc88_cell(8, 4),
        "kana" => pc88_cell(8, 5),
        "shift" => pc88_cell(8, 6),
        "ctrl" => pc88_cell(8, 7),
        // Matrix row 9.
        "stop" => pc88_cell(9, 0),
        "f1" => pc88_cell(9, 1),
        "f2" => pc88_cell(9, 2),
        "f3" => pc88_cell(9, 3),
        "f4" => pc88_cell(9, 4),
        "f5" => pc88_cell(9, 5),
        "space" => pc88_cell(9, 6),
        "esc" => pc88_cell(9, 7),
        // Matrix row 10.
        "tab" => pc88_cell(10, 0),
        "down" => pc88_cell(10, 1),
        "left" => pc88_cell(10, 2),
        "help" => pc88_cell(10, 3),
        "copy" => pc88_cell(10, 4),
        "kpminus" => pc88_cell(10, 5),
        "kpdivide" => pc88_cell(10, 6),
        "caps" => pc88_cell(10, 7),
        // Matrix row 11.
        "rollup" => pc88_cell(11, 0),
        "rolldown" => pc88_cell(11, 1),
        // Matrix rows 13-14: PC-88VA-specific keys (no PC-8801 equivalent).
        "f6" => pc88_cell(13, 0),
        "f7" => pc88_cell(13, 1),
        "f8" => pc88_cell(13, 2),
        "f9" => pc88_cell(13, 3),
        "f10" => pc88_cell(13, 4),
        "henkan" | "convert" => pc88_cell(13, 5),
        "kettei" | "decide" => pc88_cell(13, 6),
        "pc" => pc88_cell(14, 5),
        _ => return None,
    })
}

/// First function-key id on the PC-6001 wire encoding (F1). Function keys are
/// sent as ids 0x60-0x69 so the release bit (0x80) stays free for every key.
const PC60_FUNCTION_KEY_BASE: u8 = 0x60;

/// Maps a key name to a PC-6001 keycode for `key.*` config overrides. Normal
/// keys use their character code; function keys use the wire ids F1-F5.
/// A `0xNN` hex literal binds a raw keycode directly.
pub fn pc60_keycode_from_name(name: &str) -> Option<u8> {
    if let Some(code) = raw_hex_code(name) {
        return Some(code);
    }
    let lower = name.to_ascii_lowercase();
    if lower.len() == 1 {
        let character = lower.as_bytes()[0];
        if character.is_ascii_lowercase() {
            return Some(character - b'a' + b'A');
        }
        if character.is_ascii_digit() || (0x20..=0x5F).contains(&character) {
            return Some(character);
        }
    }
    Some(match lower.as_str() {
        "space" => 0x20,
        "return" | "enter" => 0x0D,
        "backspace" | "bs" => 0x08,
        "tab" => 0x09,
        "up" => 0x1E,
        "down" => 0x1F,
        "left" => 0x1D,
        "right" => 0x1C,
        "f1" => PC60_FUNCTION_KEY_BASE,
        "f2" => PC60_FUNCTION_KEY_BASE + 1,
        "f3" => PC60_FUNCTION_KEY_BASE + 2,
        "f4" => PC60_FUNCTION_KEY_BASE + 3,
        "f5" => PC60_FUNCTION_KEY_BASE + 4,
        _ => return None,
    })
}

/// Maps an MSX key name to its keycode byte (0x00-0x74). Only keys with a real
/// position in the Sony keyboard matrix are exposed. Values mirror the MSX
/// machine's own host-key translation.
pub fn msx_scancode_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "esc" => 0x00,
        "1" => 0x01,
        "2" => 0x02,
        "3" => 0x03,
        "4" => 0x04,
        "5" => 0x05,
        "6" => 0x06,
        "7" => 0x07,
        "8" => 0x08,
        "9" => 0x09,
        "0" => 0x0A,
        "minus" => 0x0B,
        "equals" => 0x0C,
        "backslash" | "yen" => 0x0D,
        "bs" => 0x0E,
        "tab" => 0x0F,
        "q" => 0x10,
        "w" => 0x11,
        "e" => 0x12,
        "r" => 0x13,
        "t" => 0x14,
        "y" => 0x15,
        "u" => 0x16,
        "i" => 0x17,
        "o" => 0x18,
        "p" => 0x19,
        "grave" => 0x1A,
        "leftbracket" => 0x1B,
        "return" => 0x1C,
        "a" => 0x1D,
        "s" => 0x1E,
        "d" => 0x1F,
        "f" => 0x20,
        "g" => 0x21,
        "h" => 0x22,
        "j" => 0x23,
        "k" => 0x24,
        "l" => 0x25,
        "semicolon" => 0x26,
        "apostrophe" => 0x27,
        "rightbracket" => 0x28,
        "z" => 0x29,
        "x" => 0x2A,
        "c" => 0x2B,
        "v" => 0x2C,
        "b" => 0x2D,
        "n" => 0x2E,
        "m" => 0x2F,
        "comma" => 0x30,
        "period" => 0x31,
        "slash" => 0x32,
        "underscore" | "nonusbackslash" => 0x33,
        "space" => 0x34,
        "ins" => 0x38,
        "del" => 0x39,
        "up" => 0x3A,
        "left" => 0x3B,
        "right" => 0x3C,
        "down" => 0x3D,
        "home" => 0x3E,
        "end" => 0x3F,
        "kpminus" => 0x40,
        "kp7" => 0x42,
        "kp8" => 0x43,
        "kp9" => 0x44,
        "kp4" => 0x46,
        "kp5" => 0x47,
        "kp6" => 0x48,
        "kp1" => 0x4A,
        "kp2" => 0x4B,
        "kp3" => 0x4C,
        "kp0" => 0x4E,
        "kpcomma" => 0x4F,
        "kpperiod" => 0x50,
        "pause" => 0x60,
        "f1" => 0x62,
        "f2" => 0x63,
        "f3" => 0x64,
        "f4" => 0x65,
        "f5" => 0x66,
        "shift" => 0x70,
        "caps" => 0x71,
        "kana" => 0x72,
        "graph" => 0x73,
        "ctrl" => 0x74,
        _ => return None,
    })
}

/// Maps a Sharp X1 key name to its host sub-id (0x00-0x7F). The sub-CPU remaps
/// these ids to virtual keys; values mirror the X1 machine's own translation.
pub fn x1_scancode_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "a" => 0x41,
        "b" => 0x42,
        "c" => 0x43,
        "d" => 0x44,
        "e" => 0x45,
        "f" => 0x46,
        "g" => 0x47,
        "h" => 0x48,
        "i" => 0x49,
        "j" => 0x4A,
        "k" => 0x4B,
        "l" => 0x4C,
        "m" => 0x4D,
        "n" => 0x4E,
        "o" => 0x4F,
        "p" => 0x50,
        "q" => 0x51,
        "r" => 0x52,
        "s" => 0x53,
        "t" => 0x54,
        "u" => 0x55,
        "v" => 0x56,
        "w" => 0x57,
        "x" => 0x58,
        "y" => 0x59,
        "z" => 0x5A,
        "0" => 0x30,
        "1" => 0x31,
        "2" => 0x32,
        "3" => 0x33,
        "4" => 0x34,
        "5" => 0x35,
        "6" => 0x36,
        "7" => 0x37,
        "8" => 0x38,
        "9" => 0x39,
        "space" => 0x20,
        "return" | "kpenter" => 0x0D,
        "bs" => 0x08,
        "del" => 0x2E,
        "ins" => 0x2D,
        "tab" => 0x09,
        "esc" => 0x1B,
        "home" => 0x24,
        "end" => 0x23,
        "pageup" => 0x21,
        "pagedown" => 0x22,
        "left" => 0x25,
        "up" => 0x26,
        "right" => 0x27,
        "down" => 0x28,
        "kp0" => 0x60,
        "kp1" => 0x61,
        "kp2" => 0x62,
        "kp3" => 0x63,
        "kp4" => 0x64,
        "kp5" => 0x65,
        "kp6" => 0x66,
        "kp7" => 0x67,
        "kp8" => 0x68,
        "kp9" => 0x69,
        "kpmultiply" => 0x6A,
        "kpplus" => 0x6B,
        "kpcomma" => 0x6C,
        "kpminus" => 0x6D,
        "kpperiod" => 0x6E,
        "kpdivide" => 0x6F,
        "semicolon" => 0x02,
        "apostrophe" => 0x01,
        "comma" => 0x04,
        "period" => 0x06,
        "slash" => 0x07,
        "minus" => 0x05,
        "grave" => 0x0A,
        "leftbracket" => 0x0B,
        "rightbracket" => 0x0E,
        "backslash" => 0x0C,
        "equals" => 0x0F,
        "shift" => 0x10,
        "ctrl" => 0x11,
        "alt" => 0x12,
        "caps" => 0x14,
        _ => return None,
    })
}

/// Maps a Fujitsu FM-7 key name to its physical scancode (0x01-0x66). Values
/// mirror the FM-7 machine's own host-key translation, plus the named KANA and
/// BREAK keys the encoder recognizes.
pub fn fm7_scancode_from_name(name: &str) -> Option<u8> {
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "esc" => 0x01,
        "1" => 0x02,
        "2" => 0x03,
        "3" => 0x04,
        "4" => 0x05,
        "5" => 0x06,
        "6" => 0x07,
        "7" => 0x08,
        "8" => 0x09,
        "9" => 0x0A,
        "0" => 0x0B,
        "minus" => 0x0C,
        "equals" => 0x0D,
        "backslash" => 0x0E,
        "bs" => 0x0F,
        "tab" => 0x10,
        "q" => 0x11,
        "w" => 0x12,
        "e" => 0x13,
        "r" => 0x14,
        "t" => 0x15,
        "y" => 0x16,
        "u" => 0x17,
        "i" => 0x18,
        "o" => 0x19,
        "p" => 0x1A,
        "grave" => 0x1B,
        "leftbracket" => 0x1C,
        "return" => 0x1D,
        "a" => 0x1E,
        "s" => 0x1F,
        "d" => 0x20,
        "f" => 0x21,
        "g" => 0x22,
        "h" => 0x23,
        "j" => 0x24,
        "k" => 0x25,
        "l" => 0x26,
        "semicolon" => 0x27,
        "apostrophe" => 0x28,
        "rightbracket" => 0x29,
        "z" => 0x2A,
        "x" => 0x2B,
        "c" => 0x2C,
        "v" => 0x2D,
        "b" => 0x2E,
        "n" => 0x2F,
        "m" => 0x30,
        "comma" => 0x31,
        "period" => 0x32,
        "slash" => 0x33,
        "underscore" | "nonusbackslash" => 0x34,
        "space" => 0x35,
        "kpmultiply" => 0x36,
        "kpdivide" => 0x37,
        "kpplus" => 0x38,
        "kpminus" => 0x39,
        "kp7" => 0x3A,
        "kp8" => 0x3B,
        "kp9" => 0x3C,
        "kp4" => 0x3E,
        "kp5" => 0x3F,
        "kp6" => 0x40,
        "kpcomma" => 0x41,
        "kp1" => 0x42,
        "kp2" => 0x43,
        "kp3" => 0x44,
        "kpenter" => 0x45,
        "kp0" => 0x46,
        "kpperiod" => 0x47,
        "home" => 0x49,
        "del" => 0x4B,
        "ins" => 0x4C,
        "up" => 0x4D,
        "left" => 0x4F,
        "down" => 0x50,
        "right" => 0x51,
        "ctrl" => 0x52,
        "shift" => 0x53,
        "rshift" => 0x54,
        "caps" => 0x55,
        "alt" | "graph" => 0x56,
        "kana" => 0x5A,
        "break" | "pause" => 0x5C,
        "f1" => 0x5D,
        "f2" => 0x5E,
        "f3" => 0x5F,
        "f4" => 0x60,
        "f5" => 0x61,
        "f6" => 0x62,
        "f7" => 0x63,
        "f8" => 0x64,
        "f9" => 0x65,
        "f10" => 0x66,
        _ => return None,
    })
}

/// Maps a PC/AT key name to its set-1 key id for the 106-key JIS (OADG) layout.
/// The E0-extended keys use the synthetic ids the machine_at crate exports. A
/// `0xNN` hex literal binds a raw id directly.
pub fn at_key_from_name(name: &str) -> Option<u8> {
    if let Some(code) = raw_hex_code(name) {
        return Some(code);
    }
    let name_lower = name.to_ascii_lowercase();
    Some(match name_lower.as_str() {
        "esc" | "escape" => 0x01,
        "1" => 0x02,
        "2" => 0x03,
        "3" => 0x04,
        "4" => 0x05,
        "5" => 0x06,
        "6" => 0x07,
        "7" => 0x08,
        "8" => 0x09,
        "9" => 0x0A,
        "0" => 0x0B,
        "minus" => 0x0C,
        "caret" | "equals" => 0x0D,
        "backspace" | "bs" => 0x0E,
        "tab" => 0x0F,
        "q" => 0x10,
        "w" => 0x11,
        "e" => 0x12,
        "r" => 0x13,
        "t" => 0x14,
        "y" => 0x15,
        "u" => 0x16,
        "i" => 0x17,
        "o" => 0x18,
        "p" => 0x19,
        "leftbracket" => 0x1A,
        "rightbracket" => 0x1B,
        "return" | "enter" => 0x1C,
        "lctrl" | "ctrl" => 0x1D,
        "a" => 0x1E,
        "s" => 0x1F,
        "d" => 0x20,
        "f" => 0x21,
        "g" => 0x22,
        "h" => 0x23,
        "j" => 0x24,
        "k" => 0x25,
        "l" => 0x26,
        "semicolon" => 0x27,
        "colon" | "apostrophe" => 0x28,
        "zenkaku" | "grave" | "hankaku" => 0x29,
        "lshift" | "shift" => 0x2A,
        "backslash" => 0x2B,
        "z" => 0x2C,
        "x" => 0x2D,
        "c" => 0x2E,
        "v" => 0x2F,
        "b" => 0x30,
        "n" => 0x31,
        "m" => 0x32,
        "comma" => 0x33,
        "period" => 0x34,
        "slash" => 0x35,
        "rshift" => 0x36,
        "kpmultiply" => 0x37,
        "lalt" | "alt" => 0x38,
        "space" => 0x39,
        "capslock" | "caps" => 0x3A,
        "f1" => 0x3B,
        "f2" => 0x3C,
        "f3" => 0x3D,
        "f4" => 0x3E,
        "f5" => 0x3F,
        "f6" => 0x40,
        "f7" => 0x41,
        "f8" => 0x42,
        "f9" => 0x43,
        "f10" => 0x44,
        "numlock" => 0x45,
        "kp7" => 0x47,
        "kp8" => 0x48,
        "kp9" => 0x49,
        "kpminus" => 0x4A,
        "kp4" => 0x4B,
        "kp5" => 0x4C,
        "kp6" => 0x4D,
        "kpplus" => 0x4E,
        "kp1" => 0x4F,
        "kp2" => 0x50,
        "kp3" => 0x51,
        "kp0" => 0x52,
        "kpperiod" => 0x53,
        "nonusbackslash" => 0x56,
        "f11" => 0x57,
        "f12" => 0x58,
        "ro" | "underscore" => 0x73,
        "kana" | "katakana" | "hiragana" => 0x70,
        "yen" => 0x7D,
        "henkan" | "xfer" => 0x79,
        "muhenkan" | "nfer" => 0x7B,
        "up" => machine_at::AT_KEY_CURSOR_UP,
        "down" => machine_at::AT_KEY_CURSOR_DOWN,
        "left" => machine_at::AT_KEY_CURSOR_LEFT,
        "right" => machine_at::AT_KEY_CURSOR_RIGHT,
        "insert" | "ins" => machine_at::AT_KEY_INSERT,
        "delete" | "del" => machine_at::AT_KEY_DELETE,
        "home" => machine_at::AT_KEY_HOME,
        "end" => machine_at::AT_KEY_END,
        "pageup" => machine_at::AT_KEY_PAGE_UP,
        "pagedown" => machine_at::AT_KEY_PAGE_DOWN,
        "kpenter" => machine_at::AT_KEY_KEYPAD_ENTER,
        "kpdivide" => machine_at::AT_KEY_KEYPAD_DIVIDE,
        "rctrl" => machine_at::AT_KEY_RIGHT_CTRL,
        "ralt" => machine_at::AT_KEY_RIGHT_ALT,
        _ => return None,
    })
}

/// Resolves a `key.<host> = <native>` binding for a target into the host
/// scancode and the raw machine-native code. Every target routes to its own
/// name table.
pub fn parse_key_binding(
    target: Target,
    host_name: &str,
    native_name: &str,
) -> Option<(Scancode, u8)> {
    let host = Scancode::from_name(host_name)?;
    let code = match target {
        Target::Pc60 => pc60_keycode_from_name(native_name),
        Target::Pc88 => pc88_matrix_code_from_name(native_name),
        Target::Pc88Va => pc88va_keycode_from_name(native_name),
        Target::Pc98 => pc98_scancode_from_name(native_name),
        Target::Msx => msx_scancode_from_name(native_name),
        Target::Towns => towns_scancode_from_name(native_name),
        Target::X68k => x68k_scancode_from_name(native_name),
        Target::X1 => x1_scancode_from_name(native_name),
        Target::Fm7 => fm7_scancode_from_name(native_name),
        Target::At => at_key_from_name(native_name),
    }?;
    Some((host, code))
}
