[package]
name = "machine_98"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
mt32 = ["device/mt32"]
sc55 = ["device/sc55"]

[dependencies]
blake3.workspace = true
common = { workspace = true, features = ["std"] }
cpu.workspace = true
device.workspace = true
dos.workspace = true
software_renderer.workspace = true

[dev-dependencies]
resampler.workspace = true
